# Generated by Django 5.1 on 2024-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('A', 'Avançado'), ('I', 'Intermediário'), ('B', 'Básico')], default='B', max_length=1),
        ),
    ]
