# Generated by Django 5.1 on 2024-08-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_course_level_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('I', 'Intermediário'), ('B', 'Básico'), ('A', 'Avançado')], default='B', max_length=1),
        ),
    ]
